Correct format portability warnings
These are from GCC 4.9, and of the form:

  error: format ‘%lld’ expects argument of type ‘long long int’, but
  argument 4 has type ‘int64_t’

This is on a platform where int64_t is a typedef for 'long int', so
the warning is fair enough.

These have been replaced with the C99 PRI constants.